# -*- coding: utf-8 -*-
"""1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D_N2otNh9Ikfjh6qJgqTNusDT8_PMsTl
"""

import random

t = [1,1,1,1,1,1]
E = ["e1","e2","e3","e4"]
H = ["h1","h2","h3","h4","h5","h6","h7","h8"]
H1 = ["h1","h2","h3","h4","h5","h6","h7","h8"]
He = []
e = []
for i in range(0,len(E)):
  n = random.randint(1,10)
  for j in range(0,n):
    n1 = random.randint(0,len(H)-1)
    if H[n1] not in e:
      e.append(H[n1])
  He.append(e)
  e = []

print(He)

for u in range(0,len(He)):
  for g in range(0,len(He[u])):
    if He[u][g] in H:
      H.remove(He[u][g])
  
while len(H)>0:
  He[0].append(H[-1])
  H.pop()

print(He)
def myFunc(e):
  return len(e)

He.sort(key=myFunc)
#print(He)
He1 = He


def myFunc1(e):
  return e[-1]

for x in range(0,len(He1)):
  He1[x].append(x)

for x in range(0,len(He1)):
  He1[x].append(0)
print(He1)

print(He1)
j = 0
i = len(H1)-1

while i+1 > 0:
  for j in range(0,len(E)):
    if H1[i] in He1[j]:
      
      print(H1[i])
      He1[j][-1] += 1
      He1[j].remove(H1[i])
      H1.pop()
      break
  j = 0
  i = len(H1)-1
  He1.sort(key=myFunc1)
  print(He1)

L = []
i = 0

for i in range(0,len(He1)):
  L.append(He1[i][-1])
print("")
print("Max Load: "+ str(max(L)))
print(He1)
#print(A)